# Site settings
title: SZ
header-img: img/home-bg.jpg
email: szimmer1@ucsc.edu
description: "Let's not get technical"
baseurl: ""
url: "http://www.shaharzimmerman.com"
twitter_username: GnarShahar
github_username:  szimmer1
about: Shahar is graduating from UC Santa Cruz in June with a BS/BA in Biochemistry and Computer Science. He's a 5th year and vehemently insists that 5 is the new 4. Shahar's hobbies are surfing, rock climbing, and (soon) kitesurfing. His current interests are Docker, learning C++, and getting "real solid" at problem-solving using data structures. His not-current interests are music and finances. He lives in Santa Cruz.
brief_about: Shahar is graduating from UC Santa Cruz in June with a BS/BA in Biochemistry and Computer Science. His current interests are Docker, learning C++, and getting "real solid" at problem-solving using data structures.
fbAppId: 819875781392896

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: [".idea","less","node_modules","Gruntfile.js","package.json","README.md"]
